"""Catalog data access — services must not read global mock dictionaries directly."""

from typing import Protocol

from app.domain.models import EngineerProfile, ProjectProfile
from app.schemas.engineer import EngineerProfile as LegacyEngineerProfile
from app.schemas.project_fit import ProjectRequirements


class CatalogRepository(Protocol):
    def list_engineer_names(self) -> list[str]: ...

    def get_legacy_engineer(self, name: str) -> LegacyEngineerProfile | None: ...

    def list_legacy_engineers(self) -> list[LegacyEngineerProfile]: ...

    def get_legacy_project(self, name: str) -> ProjectRequirements | None: ...

    def resolve_engineer_name(self, name: str) -> str | None: ...

    def get_domain_engineers(self) -> list[EngineerProfile]: ...

    def get_domain_project(self, name: str) -> ProjectProfile | None: ...
