"""Deterministic NovaBank identity catalog (extends foundational seed keys)."""

from __future__ import annotations

# Existing foundational codes/slugs are preserved exactly for ID stability.

BUSINESS_UNITS: list[tuple[str, str]] = [
    ("Consumer Banking", "retail-banking"),  # foundational code preserved
    ("Enterprise Platforms and Cloud", "enterprise-platforms"),
    ("Payments and Money Movement", "payments-money-movement"),
    ("Risk, Fraud and Compliance Technology", "risk-fraud-compliance"),
    ("Data and Customer Intelligence", "data-customer-intelligence"),
]

DEPARTMENTS: list[tuple[str, str, str]] = [
    ("Payments Engineering", "payments-eng", "retail-banking"),
    ("Digital Channels", "digital-channels", "retail-banking"),
    ("Cloud Platform", "cloud-platform", "enterprise-platforms"),
    ("Data & Fraud", "data-fraud", "enterprise-platforms"),
    ("Payment APIs", "payment-apis", "payments-money-movement"),
    ("Card & Rail Ops", "card-rail-ops", "payments-money-movement"),
    ("Identity & Access", "identity-access", "risk-fraud-compliance"),
    ("Compliance Technology", "compliance-tech", "risk-fraud-compliance"),
    ("Customer Intelligence", "customer-intel", "data-customer-intelligence"),
    ("AI Experience", "ai-experience", "data-customer-intelligence"),
]

# Exactly 10 teams. Foundational six slugs preserved; four additive teams.
TEAMS: list[tuple[str, str, str, str, str]] = [
    # name, slug, dept_code, team_type, mission
    (
        "Payment Processing",
        "payments-core",
        "payments-eng",
        "product",
        "Own ledger and payment processing services.",
    ),
    (
        "Payment Rails",
        "payments-rails",
        "payments-eng",
        "product",
        "Deliver real-time payment rails and settlement adapters.",
    ),
    (
        "Digital Banking Experience",
        "mobile-banking",
        "digital-channels",
        "product",
        "Consumer mobile and digital banking experience.",
    ),
    (
        "Cloud Foundation",
        "cloud-foundations",
        "cloud-platform",
        "platform",
        "Shared Azure landing zones and platform capacity (overcommitted).",
    ),
    (
        "Developer Platform",
        "site-reliability",
        "cloud-platform",
        "sre",
        "SRE, SLO platform and developer reliability tooling.",
    ),
    (
        "Fraud Decisioning",
        "fraud-detection",
        "data-fraud",
        "data",
        "Fraud scoring models and decisioning pipelines.",
    ),
    (
        "Customer Identity",
        "customer-identity",
        "identity-access",
        "product",
        "Customer identity, authN/Z and session services.",
    ),
    (
        "Payment API Platform",
        "payment-api-platform",
        "payment-apis",
        "platform",
        "Shared payment API gateway and partner interfaces.",
    ),
    (
        "Compliance Data",
        "compliance-data",
        "compliance-tech",
        "data",
        "Regulatory reporting and compliance data products.",
    ),
    (
        "Customer Copilot",
        "customer-copilot",
        "ai-experience",
        "product",
        "Customer-facing AI copilot orchestration and evaluation.",
    ),
]

# Foundational 15 engineers preserved; eng-16..eng-48 additive fictional profiles.
ENGINEERS: list[tuple[str, str, str, str]] = [
    ("Ada Nguyen", "eng-01", "payments-core", "senior"),
    ("Ben Carter", "eng-02", "payments-core", "mid"),
    ("Chloe Park", "eng-03", "payments-rails", "staff"),
    ("Diego Ruiz", "eng-04", "payments-rails", "mid"),
    ("Ezra Cohen", "eng-05", "mobile-banking", "senior"),
    ("Farah Idris", "eng-06", "mobile-banking", "junior"),
    ("Gita Rao", "eng-07", "cloud-foundations", "principal"),
    ("Hugo Silva", "eng-08", "cloud-foundations", "senior"),
    ("Ivy Chen", "eng-09", "cloud-foundations", "mid"),
    ("Jonas Weber", "eng-10", "site-reliability", "staff"),
    ("Kira Novak", "eng-11", "site-reliability", "mid"),
    ("Liam Osei", "eng-12", "fraud-detection", "senior"),
    ("Maya Kapoor", "eng-13", "fraud-detection", "senior"),
    ("Noah Kim", "eng-14", "fraud-detection", "mid"),
    ("Olivia Braun", "eng-15", "payments-core", "junior"),
    ("Priya Nair", "eng-16", "customer-identity", "staff"),
    ("Quinn Blake", "eng-17", "customer-identity", "senior"),
    ("Ravi Mehta", "eng-18", "customer-identity", "mid"),
    ("Sara Lind", "eng-19", "customer-identity", "junior"),
    ("Theo Marais", "eng-20", "payment-api-platform", "staff"),
    ("Uma Desai", "eng-21", "payment-api-platform", "senior"),
    ("Victor Holm", "eng-22", "payment-api-platform", "mid"),
    ("Wendy Zhao", "eng-23", "payment-api-platform", "mid"),
    ("Xavier Okonkwo", "eng-24", "compliance-data", "senior"),
    ("Yara Haddad", "eng-25", "compliance-data", "mid"),
    ("Zane Ortiz", "eng-26", "compliance-data", "junior"),
    ("Aisha Rahman", "eng-27", "compliance-data", "senior"),
    ("Bruno Costa", "eng-28", "customer-copilot", "staff"),
    ("Celia Frost", "eng-29", "customer-copilot", "senior"),
    ("Dev Patel", "eng-30", "customer-copilot", "mid"),
    ("Elena Rossi", "eng-31", "customer-copilot", "mid"),
    ("Felix Andersson", "eng-32", "customer-copilot", "junior"),
    ("Gina Moreau", "eng-33", "payments-core", "mid"),
    ("Hiro Tanaka", "eng-34", "payments-rails", "senior"),
    ("Ines Carvalho", "eng-35", "mobile-banking", "mid"),
    ("Jamal Brooks", "eng-36", "cloud-foundations", "senior"),
    ("Katya Volkov", "eng-37", "cloud-foundations", "mid"),
    ("Leo Martins", "eng-38", "site-reliability", "senior"),
    ("Mira Sen", "eng-39", "site-reliability", "junior"),
    ("Nia Okeke", "eng-40", "fraud-detection", "mid"),
    ("Owen Fraser", "eng-41", "fraud-detection", "junior"),
    ("Paula Niemi", "eng-42", "payments-rails", "junior"),
    ("Reza Amari", "eng-43", "payment-api-platform", "junior"),
    ("Sofia Bergman", "eng-44", "mobile-banking", "senior"),
    ("Tomás Alvarez", "eng-45", "customer-identity", "mid"),
    ("Uche Nwosu", "eng-46", "compliance-data", "mid"),
    ("Vera Solis", "eng-47", "cloud-foundations", "junior"),
    ("Will Jensen", "eng-48", "site-reliability", "mid"),
]

CAPABILITIES: list[tuple[str, str, str]] = [
    ("Payments Processing", "payments-processing", "backend"),
    ("Cloud Architecture", "cloud-architecture", "cloud"),
    ("Azure Platform", "azure-platform", "cloud"),
    ("Fraud Modeling", "fraud-modeling", "ai"),
    ("Data Engineering", "data-engineering", "data"),
    ("Site Reliability", "site-reliability", "devops"),
    ("Mobile Engineering", "mobile-engineering", "backend"),
    ("Security Engineering", "security-engineering", "security"),
    ("Identity Platform", "identity-platform", "security"),
    ("Payment APIs", "payment-apis", "backend"),
    ("Compliance Reporting", "compliance-reporting", "data"),
    ("Customer Copilot AI", "customer-copilot-ai", "ai"),
    ("Event Streaming", "event-streaming", "backend"),
    ("API Gateway", "api-gateway", "architecture"),
    ("Observability Engineering", "observability-engineering", "devops"),
    ("Data Governance", "data-governance", "data"),
    ("Threat Detection", "threat-detection", "security"),
    ("Experience Design Systems", "experience-design-systems", "delivery_execution"),
]

SKILLS: list[tuple[str, str, str]] = [
    ("Kubernetes", "kubernetes", "cloud"),
    ("Terraform", "terraform", "cloud"),
    ("Kafka", "kafka", "backend"),
    ("Python", "python", "backend"),
    ("Spark", "spark", "data"),
    ("Kotlin", "kotlin", "backend"),
    ("Threat Modeling", "threat-modeling", "security"),
    ("Observability", "observability", "devops"),
    ("OAuth", "oauth", "security"),
    ("OpenAPI", "openapi", "backend"),
    ("dbt", "dbt", "data"),
    ("Prompt Evaluation", "prompt-evaluation", "ai"),
    ("Azure Policy", "azure-policy", "cloud"),
    ("React", "react", "delivery_execution"),
    ("Go", "go", "backend"),
    ("SQL", "sql", "data"),
]

CAPABILITY_SKILLS: list[tuple[str, str]] = [
    ("cloud-architecture", "kubernetes"),
    ("cloud-architecture", "terraform"),
    ("azure-platform", "terraform"),
    ("azure-platform", "azure-policy"),
    ("payments-processing", "kafka"),
    ("payments-processing", "python"),
    ("fraud-modeling", "spark"),
    ("mobile-engineering", "kotlin"),
    ("security-engineering", "threat-modeling"),
    ("site-reliability", "observability"),
    ("identity-platform", "oauth"),
    ("payment-apis", "openapi"),
    ("payment-apis", "go"),
    ("compliance-reporting", "dbt"),
    ("compliance-reporting", "sql"),
    ("customer-copilot-ai", "prompt-evaluation"),
    ("customer-copilot-ai", "python"),
    ("event-streaming", "kafka"),
    ("api-gateway", "openapi"),
    ("observability-engineering", "observability"),
    ("data-governance", "sql"),
    ("threat-detection", "threat-modeling"),
    ("experience-design-systems", "react"),
    ("data-engineering", "spark"),
]

INITIATIVES: list[tuple[str, str, str, str]] = [
    ("Payment Modernization", "payment-modernization", "critical", "critical"),
    ("Azure Migration", "azure-migration", "high", "high"),
    ("Fraud Detection Uplift", "fraud-detection-uplift", "critical", "critical"),
    ("Mobile Refresh", "mobile-refresh", "medium", "medium"),
    ("Reliability Program", "reliability-program", "medium", "high"),
    ("Customer Copilot Launch", "customer-copilot-launch", "high", "critical"),
    ("Card Issuing Platform", "card-issuing-platform", "high", "high"),
    ("Open Banking APIs", "open-banking-apis", "medium", "high"),
    ("Identity Resilience", "identity-resilience", "high", "critical"),
    ("Compliance Reporting Overhaul", "compliance-reporting-overhaul", "medium", "high"),
    ("Developer Portal", "developer-portal", "medium", "medium"),
    ("Data Platform Foundations", "data-platform-foundations", "high", "high"),
    ("Threat Detection Expansion", "threat-detection-expansion", "medium", "high"),
    ("Experience Design System", "experience-design-system", "low", "medium"),
]

PROJECTS: list[tuple[str, str, str, str]] = [
    ("Real-Time Payments Rail", "rt-payments-rail", "payment-modernization", "payments-rails"),
    ("Ledger Modernization", "ledger-modernization", "payment-modernization", "payments-core"),
    ("Core Banking to Azure", "core-banking-azure", "azure-migration", "cloud-foundations"),
    ("Data Lake Migration", "data-lake-migration", "azure-migration", "fraud-detection"),
    ("Fraud Scoring v2", "fraud-scoring-v2", "fraud-detection-uplift", "fraud-detection"),
    ("Mobile App 4.0", "mobile-app-4", "mobile-refresh", "mobile-banking"),
    ("SLO Platform", "slo-platform", "reliability-program", "site-reliability"),
    ("Payments Observability", "payments-observability", "reliability-program", "payments-core"),
    (
        "Copilot Orchestration",
        "copilot-orchestration",
        "customer-copilot-launch",
        "customer-copilot",
    ),
    (
        "Copilot Evaluation Harness",
        "copilot-eval-harness",
        "customer-copilot-launch",
        "customer-copilot",
    ),
    ("Card Issuing Core", "card-issuing-core", "card-issuing-platform", "payments-core"),
    ("Card Authorization Edge", "card-auth-edge", "card-issuing-platform", "payment-api-platform"),
    ("Open Banking Consent", "open-banking-consent", "open-banking-apis", "customer-identity"),
    (
        "Open Banking Accounts API",
        "open-banking-accounts",
        "open-banking-apis",
        "payment-api-platform",
    ),
    (
        "Identity Gateway Hardening",
        "identity-gateway-hardening",
        "identity-resilience",
        "customer-identity",
    ),
    ("Session Risk Signals", "session-risk-signals", "identity-resilience", "fraud-detection"),
    (
        "Regulatory Ledger Extract",
        "regulatory-ledger-extract",
        "compliance-reporting-overhaul",
        "compliance-data",
    ),
    ("SAR Workflow Automation", "sar-workflow", "compliance-reporting-overhaul", "compliance-data"),
    ("Internal Developer Portal", "internal-dev-portal", "developer-portal", "site-reliability"),
    ("Platform Self-Service", "platform-self-service", "developer-portal", "cloud-foundations"),
    (
        "Customer 360 Warehouse",
        "customer-360-warehouse",
        "data-platform-foundations",
        "compliance-data",
    ),
    (
        "Streaming Ingestion Fabric",
        "streaming-ingestion",
        "data-platform-foundations",
        "fraud-detection",
    ),
    (
        "Threat Detection Ruleset",
        "threat-detection-ruleset",
        "threat-detection-expansion",
        "fraud-detection",
    ),
    (
        "Design System Components",
        "design-system-components",
        "experience-design-system",
        "mobile-banking",
    ),
]

REPOSITORIES: list[tuple[str, str]] = [
    ("payments-core-svc", "cloud-foundations"),
    ("payments-rails-svc", "payments-rails"),
    ("ledger-svc", "payments-core"),
    ("mobile-android", "mobile-banking"),
    ("mobile-ios", "mobile-banking"),
    ("cloud-landing-zone", "cloud-foundations"),
    ("fraud-scoring", "fraud-detection"),
    ("data-lake-pipelines", "fraud-detection"),
    ("slo-controller", "site-reliability"),
    ("observability-stack", "site-reliability"),
    ("identity-gateway", "customer-identity"),
    ("session-service", "customer-identity"),
    ("payment-api-gateway", "payment-api-platform"),
    ("partner-api-sdk", "payment-api-platform"),
    ("compliance-reporting", "compliance-data"),
    ("regulatory-extracts", "compliance-data"),
    ("customer-copilot-svc", "customer-copilot"),
    ("copilot-eval-harness", "customer-copilot"),
    ("azure-policy-packs", "cloud-foundations"),
    ("developer-portal", "site-reliability"),
    ("card-issuing-svc", "payments-core"),
    ("card-auth-edge", "payment-api-platform"),
    ("open-banking-consent", "customer-identity"),
    ("open-banking-accounts", "payment-api-platform"),
    ("streaming-ingestion", "fraud-detection"),
    ("customer-360", "compliance-data"),
    ("threat-rules", "fraud-detection"),
    ("design-system", "mobile-banking"),
    ("platform-self-service", "cloud-foundations"),
    ("payments-contracts", "payment-api-platform"),
    ("incident-runbooks", "site-reliability"),
    ("evidence-freshness-probe", "customer-copilot"),
]

# Story hooks: concentrated ownership subjects (bounded subset).
CONCENTRATED_REPOS = ("fraud-scoring", "data-lake-pipelines", "evidence-freshness-probe")
HEALTHY_COMPARISON_REPOS = (
    "payments-rails-svc",
    "ledger-svc",
    "identity-gateway",
    "slo-controller",
)
STALE_EVIDENCE_INITIATIVE = "customer-copilot-launch"
OVERCOMMITTED_TEAM = "cloud-foundations"
ELEVATED_INCIDENT_REPOS = ("payments-core-svc", "cloud-landing-zone", "fraud-scoring")
