"""initial_persistence_schema

Revision ID: d573b27e3974
Revises: 
Create Date: 2026-07-22 21:33:02.990661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd573b27e3974'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('audit_event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_record_id', sa.Uuid(), nullable=False),
    sa.Column('actor_reference', sa.String(length=256), nullable=True),
    sa.Column('event_version', sa.String(length=16), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('audit_event_id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_aggregate', 'audit_events', ['aggregate_type', 'aggregate_record_id'], unique=False)
    op.create_index('ix_audit_events_occurred_at', 'audit_events', ['occurred_at'], unique=False)
    op.create_table('capabilities',
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('capability_id', name=op.f('pk_capabilities'))
    )
    op.create_table('engineers',
    sa.Column('engineer_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role_title', sa.String(length=128), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=False),
    sa.Column('has_certifications', sa.Boolean(), nullable=False),
    sa.Column('has_project_history', sa.Boolean(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('engineer_id', name=op.f('pk_engineers'))
    )
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_projects'))
    )
    op.create_table('assessments',
    sa.Column('assessment_record_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('result_snapshot', sa.JSON(), nullable=False),
    sa.Column('result_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_reference', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_assessments_project_id_projects')),
    sa.PrimaryKeyConstraint('assessment_record_id', name=op.f('pk_assessments'))
    )
    op.create_index('ix_assessments_assessment_id', 'assessments', ['assessment_id'], unique=False)
    op.create_index('ix_assessments_created_at', 'assessments', ['created_at'], unique=False)
    op.create_index('ix_assessments_project_id', 'assessments', ['project_id'], unique=False)
    op.create_table('demo_scenarios',
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('baseline_engineer_ids', sa.JSON(), nullable=False),
    sa.Column('simulation_operation', sa.JSON(), nullable=True),
    sa.Column('scenario_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_demo_scenarios_project_id_projects')),
    sa.PrimaryKeyConstraint('scenario_id', name=op.f('pk_demo_scenarios')),
    sa.UniqueConstraint('name', name=op.f('uq_demo_scenarios_name'))
    )
    op.create_table('engineer_capabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engineer_id', sa.String(length=64), nullable=False),
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('proficiency', sa.Integer(), nullable=False),
    sa.Column('evidence_sources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.capability_id'], name=op.f('fk_engineer_capabilities_capability_id_capabilities')),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.engineer_id'], name=op.f('fk_engineer_capabilities_engineer_id_engineers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engineer_capabilities')),
    sa.UniqueConstraint('engineer_id', 'capability_id', name='uq_engineer_capability')
    )
    op.create_index(op.f('ix_engineer_capabilities_capability_id'), 'engineer_capabilities', ['capability_id'], unique=False)
    op.create_index(op.f('ix_engineer_capabilities_engineer_id'), 'engineer_capabilities', ['engineer_id'], unique=False)
    op.create_table('project_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('critical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.capability_id'], name=op.f('fk_project_requirements_capability_id_capabilities')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_project_requirements_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_requirements')),
    sa.UniqueConstraint('project_id', 'capability_id', name='uq_project_capability')
    )
    op.create_index(op.f('ix_project_requirements_capability_id'), 'project_requirements', ['capability_id'], unique=False)
    op.create_index(op.f('ix_project_requirements_project_id'), 'project_requirements', ['project_id'], unique=False)
    op.create_table('simulations',
    sa.Column('simulation_record_id', sa.Uuid(), nullable=False),
    sa.Column('simulation_id', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('operation_type', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('baseline_snapshot', sa.JSON(), nullable=False),
    sa.Column('baseline_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('proposed_snapshot', sa.JSON(), nullable=False),
    sa.Column('proposed_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('result_snapshot', sa.JSON(), nullable=False),
    sa.Column('result_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('readiness_delta', sa.Integer(), nullable=False),
    sa.Column('confidence_delta', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_reference', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_simulations_project_id_projects')),
    sa.PrimaryKeyConstraint('simulation_record_id', name=op.f('pk_simulations'))
    )
    op.create_index('ix_simulations_created_at', 'simulations', ['created_at'], unique=False)
    op.create_index('ix_simulations_project_id', 'simulations', ['project_id'], unique=False)
    op.create_index('ix_simulations_simulation_id', 'simulations', ['simulation_id'], unique=False)
    op.create_table('assessment_decision_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_record_id', sa.Uuid(), nullable=False),
    sa.Column('step', sa.String(length=32), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('policy_version', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_record_id'], ['assessments.assessment_record_id'], name=op.f('fk_assessment_decision_traces_assessment_record_id_assessments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_decision_traces'))
    )
    op.create_index(op.f('ix_assessment_decision_traces_assessment_record_id'), 'assessment_decision_traces', ['assessment_record_id'], unique=False)
    op.create_table('assessment_risk_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_record_id', sa.Uuid(), nullable=False),
    sa.Column('finding_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('capability_id', sa.String(length=64), nullable=True),
    sa.Column('engineer_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_record_id'], ['assessments.assessment_record_id'], name=op.f('fk_assessment_risk_findings_assessment_record_id_assessments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_risk_findings'))
    )
    op.create_index(op.f('ix_assessment_risk_findings_assessment_record_id'), 'assessment_risk_findings', ['assessment_record_id'], unique=False)
    op.create_table('human_reviews',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_record_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewer_reference', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['assessment_record_id'], ['assessments.assessment_record_id'], name=op.f('fk_human_reviews_assessment_record_id_assessments')),
    sa.PrimaryKeyConstraint('review_id', name=op.f('pk_human_reviews'))
    )
    op.create_index('ix_human_reviews_assessment_record_id', 'human_reviews', ['assessment_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_human_reviews_assessment_record_id', table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index(op.f('ix_assessment_risk_findings_assessment_record_id'), table_name='assessment_risk_findings')
    op.drop_table('assessment_risk_findings')
    op.drop_index(op.f('ix_assessment_decision_traces_assessment_record_id'), table_name='assessment_decision_traces')
    op.drop_table('assessment_decision_traces')
    op.drop_index('ix_simulations_simulation_id', table_name='simulations')
    op.drop_index('ix_simulations_project_id', table_name='simulations')
    op.drop_index('ix_simulations_created_at', table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_project_requirements_project_id'), table_name='project_requirements')
    op.drop_index(op.f('ix_project_requirements_capability_id'), table_name='project_requirements')
    op.drop_table('project_requirements')
    op.drop_index(op.f('ix_engineer_capabilities_engineer_id'), table_name='engineer_capabilities')
    op.drop_index(op.f('ix_engineer_capabilities_capability_id'), table_name='engineer_capabilities')
    op.drop_table('engineer_capabilities')
    op.drop_table('demo_scenarios')
    op.drop_index('ix_assessments_project_id', table_name='assessments')
    op.drop_index('ix_assessments_created_at', table_name='assessments')
    op.drop_index('ix_assessments_assessment_id', table_name='assessments')
    op.drop_table('assessments')
    op.drop_table('projects')
    op.drop_table('engineers')
    op.drop_table('capabilities')
    op.drop_index('ix_audit_events_occurred_at', table_name='audit_events')
    op.drop_index('ix_audit_events_aggregate', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
