"""enterprise data foundation

Revision ID: p3_enterprise_foundation
Revises: a1b2c3d4e5f6
Create Date: 2026-07-28 01:18:54.138075

Additive Phase 3 Prompt 1 migration:
- Creates the tenant-scoped enterprise data-foundation tables (ent_*).
- Adds a nullable compatibility ``tenant_id`` column to the pre-existing Phase 2
  catalog tables (capabilities, engineers, projects) and backfills existing rows
  to the deterministic legacy tenant. The column is intentionally left nullable
  so Phase 2 write paths remain non-breaking. No Phase 2 assessment, simulation,
  review, audit or leadership-brief history is touched.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types

# Deterministic legacy/demo tenant used to backfill pre-Phase-3 catalog rows.
LEGACY_TENANT_ID = "legacy-default"


# revision identifiers, used by Alembic.
revision: str = 'p3_enterprise_foundation'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ent_availabilities',
    sa.Column('availability_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('availability_percentage', sa.Integer(), nullable=True),
    sa.Column('capacity_units', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('availability_percentage IS NULL OR (availability_percentage >= 0 AND availability_percentage <= 100)', name=op.f('ck_ent_availabilities_availability_percentage_bounds')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_ent_availabilities_confidence_bounds')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_ent_availabilities_availability_interval')),
    sa.PrimaryKeyConstraint('availability_id', name=op.f('pk_ent_availabilities')),
    sa.UniqueConstraint('tenant_id', 'target_type', 'target_id', 'start_time', name='uq_ent_availabilities_window')
    )
    op.create_index(op.f('ix_ent_availabilities_target_id'), 'ent_availabilities', ['target_id'], unique=False)
    op.create_index(op.f('ix_ent_availabilities_tenant_id'), 'ent_availabilities', ['tenant_id'], unique=False)
    op.create_table('ent_capabilities',
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('capability_id', name=op.f('pk_ent_capabilities')),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_ent_capabilities_tenant_slug')
    )
    op.create_index(op.f('ix_ent_capabilities_tenant_id'), 'ent_capabilities', ['tenant_id'], unique=False)
    op.create_table('ent_data_sources',
    sa.Column('data_source_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('credential_reference', sa.String(length=256), nullable=True),
    sa.Column('config_reference', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('permission_classification', sa.String(length=16), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('data_source_id', name=op.f('pk_ent_data_sources')),
    sa.UniqueConstraint('tenant_id', 'source_type', 'display_name', name='uq_ent_data_sources_name')
    )
    op.create_index(op.f('ix_ent_data_sources_tenant_id'), 'ent_data_sources', ['tenant_id'], unique=False)
    op.create_table('ent_dependencies',
    sa.Column('dependency_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('dependency_type', sa.String(length=32), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_reference', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_type <> target_type OR source_id <> target_id', name=op.f('ck_ent_dependencies_no_self_dependency')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_ent_dependencies_valid_interval')),
    sa.PrimaryKeyConstraint('dependency_id', name=op.f('pk_ent_dependencies')),
    sa.UniqueConstraint('tenant_id', 'source_type', 'source_id', 'target_type', 'target_id', 'dependency_type', name='uq_ent_dependencies_edge')
    )
    op.create_index(op.f('ix_ent_dependencies_source_id'), 'ent_dependencies', ['source_id'], unique=False)
    op.create_index(op.f('ix_ent_dependencies_target_id'), 'ent_dependencies', ['target_id'], unique=False)
    op.create_index(op.f('ix_ent_dependencies_tenant_id'), 'ent_dependencies', ['tenant_id'], unique=False)
    op.create_table('ent_organizations',
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('organization_type', sa.String(length=32), nullable=False),
    sa.Column('timezone_name', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('organization_id', name=op.f('pk_ent_organizations')),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_ent_organizations_tenant_slug'),
    sa.UniqueConstraint('tenant_id', name='uq_ent_organizations_tenant')
    )
    op.create_index(op.f('ix_ent_organizations_tenant_id'), 'ent_organizations', ['tenant_id'], unique=False)
    op.create_table('ent_ownerships',
    sa.Column('ownership_id', sa.String(length=64), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('ownership_type', sa.String(length=16), nullable=False),
    sa.Column('allocation', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_reference', sa.String(length=256), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('allocation IS NULL OR (allocation >= 0 AND allocation <= 100)', name=op.f('ck_ent_ownerships_allocation_bounds')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_ent_ownerships_valid_interval')),
    sa.PrimaryKeyConstraint('ownership_id', name=op.f('pk_ent_ownerships')),
    sa.UniqueConstraint('tenant_id', 'owner_type', 'owner_id', 'resource_type', 'resource_id', 'ownership_type', name='uq_ent_ownerships_edge')
    )
    op.create_index(op.f('ix_ent_ownerships_owner_id'), 'ent_ownerships', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ent_ownerships_resource_id'), 'ent_ownerships', ['resource_id'], unique=False)
    op.create_index(op.f('ix_ent_ownerships_tenant_id'), 'ent_ownerships', ['tenant_id'], unique=False)
    op.create_table('ent_skills',
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('skill_id', name=op.f('pk_ent_skills')),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_ent_skills_tenant_slug')
    )
    op.create_index(op.f('ix_ent_skills_tenant_id'), 'ent_skills', ['tenant_id'], unique=False)
    op.create_table('ent_business_units',
    sa.Column('business_unit_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_ent_business_units_valid_interval')),
    sa.ForeignKeyConstraint(['organization_id'], ['ent_organizations.organization_id'], name=op.f('fk_ent_business_units_organization_id_ent_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('business_unit_id', name=op.f('pk_ent_business_units')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_ent_business_units_tenant_code')
    )
    op.create_index(op.f('ix_ent_business_units_organization_id'), 'ent_business_units', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ent_business_units_tenant_id'), 'ent_business_units', ['tenant_id'], unique=False)
    op.create_table('ent_capability_requirements',
    sa.Column('requirement_id', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_ent_capability_requirements_confidence_bounds')),
    sa.CheckConstraint('required_level >= 0 AND required_level <= 100', name=op.f('ck_ent_capability_requirements_required_level_bounds')),
    sa.ForeignKeyConstraint(['capability_id'], ['ent_capabilities.capability_id'], name=op.f('fk_ent_capability_requirements_capability_id_ent_capabilities'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('requirement_id', name=op.f('pk_ent_capability_requirements')),
    sa.UniqueConstraint('tenant_id', 'subject_type', 'subject_id', 'capability_id', name='uq_ent_capability_requirements')
    )
    op.create_index(op.f('ix_ent_capability_requirements_capability_id'), 'ent_capability_requirements', ['capability_id'], unique=False)
    op.create_index(op.f('ix_ent_capability_requirements_subject_id'), 'ent_capability_requirements', ['subject_id'], unique=False)
    op.create_index(op.f('ix_ent_capability_requirements_tenant_id'), 'ent_capability_requirements', ['tenant_id'], unique=False)
    op.create_table('ent_capability_skills',
    sa.Column('capability_skill_id', sa.String(length=64), nullable=False),
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['ent_capabilities.capability_id'], name=op.f('fk_ent_capability_skills_capability_id_ent_capabilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['ent_skills.skill_id'], name=op.f('fk_ent_capability_skills_skill_id_ent_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capability_skill_id', name=op.f('pk_ent_capability_skills')),
    sa.UniqueConstraint('tenant_id', 'capability_id', 'skill_id', name='uq_ent_capability_skills_unique')
    )
    op.create_index(op.f('ix_ent_capability_skills_capability_id'), 'ent_capability_skills', ['capability_id'], unique=False)
    op.create_index(op.f('ix_ent_capability_skills_skill_id'), 'ent_capability_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_ent_capability_skills_tenant_id'), 'ent_capability_skills', ['tenant_id'], unique=False)
    op.create_table('ent_ingestion_runs',
    sa.Column('ingestion_run_id', sa.String(length=64), nullable=False),
    sa.Column('data_source_id', sa.String(length=64), nullable=False),
    sa.Column('run_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor', app.db.types.PortableJSON(), nullable=True),
    sa.Column('records_read', sa.Integer(), nullable=False),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('error_category', sa.String(length=32), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('processing_version', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['ent_data_sources.data_source_id'], name=op.f('fk_ent_ingestion_runs_data_source_id_ent_data_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ingestion_run_id', name=op.f('pk_ent_ingestion_runs'))
    )
    op.create_index(op.f('ix_ent_ingestion_runs_data_source_id'), 'ent_ingestion_runs', ['data_source_id'], unique=False)
    op.create_index('ix_ent_ingestion_runs_source', 'ent_ingestion_runs', ['tenant_id', 'data_source_id'], unique=False)
    op.create_index(op.f('ix_ent_ingestion_runs_tenant_id'), 'ent_ingestion_runs', ['tenant_id'], unique=False)
    op.create_table('ent_initiatives',
    sa.Column('initiative_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategic_priority', sa.String(length=16), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_target', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['ent_organizations.organization_id'], name=op.f('fk_ent_initiatives_organization_id_ent_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('initiative_id', name=op.f('pk_ent_initiatives')),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_ent_initiatives_tenant_slug')
    )
    op.create_index(op.f('ix_ent_initiatives_organization_id'), 'ent_initiatives', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ent_initiatives_tenant_id'), 'ent_initiatives', ['tenant_id'], unique=False)
    op.create_table('ent_departments',
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('business_unit_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['ent_business_units.business_unit_id'], name=op.f('fk_ent_departments_business_unit_id_ent_business_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('department_id', name=op.f('pk_ent_departments')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_ent_departments_tenant_code')
    )
    op.create_index(op.f('ix_ent_departments_business_unit_id'), 'ent_departments', ['business_unit_id'], unique=False)
    op.create_index(op.f('ix_ent_departments_tenant_id'), 'ent_departments', ['tenant_id'], unique=False)
    op.create_table('ent_evidence_signals',
    sa.Column('evidence_signal_id', sa.String(length=64), nullable=False),
    sa.Column('data_source_id', sa.String(length=64), nullable=False),
    sa.Column('ingestion_run_id', sa.String(length=64), nullable=True),
    sa.Column('source_record_id', sa.String(length=256), nullable=False),
    sa.Column('signal_type', sa.String(length=32), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('processing_version', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('permission_classification', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', app.db.types.PortableJSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('provenance', app.db.types.PortableJSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_ent_evidence_signals_confidence_bounds')),
    sa.ForeignKeyConstraint(['data_source_id'], ['ent_data_sources.data_source_id'], name=op.f('fk_ent_evidence_signals_data_source_id_ent_data_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ent_ingestion_runs.ingestion_run_id'], name=op.f('fk_ent_evidence_signals_ingestion_run_id_ent_ingestion_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('evidence_signal_id', name=op.f('pk_ent_evidence_signals')),
    sa.UniqueConstraint('tenant_id', 'data_source_id', 'source_record_id', 'signal_type', 'payload_hash', name='uq_ent_evidence_signals_dedup')
    )
    op.create_index(op.f('ix_ent_evidence_signals_data_source_id'), 'ent_evidence_signals', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_ent_evidence_signals_ingestion_run_id'), 'ent_evidence_signals', ['ingestion_run_id'], unique=False)
    op.create_index('ix_ent_evidence_signals_subject', 'ent_evidence_signals', ['tenant_id', 'subject_type', 'subject_id'], unique=False)
    op.create_index(op.f('ix_ent_evidence_signals_tenant_id'), 'ent_evidence_signals', ['tenant_id'], unique=False)
    op.create_table('ent_teams',
    sa.Column('team_id', sa.String(length=64), nullable=False),
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('team_type', sa.String(length=32), nullable=False),
    sa.Column('capacity_points', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('capacity_points IS NULL OR (capacity_points >= 0 AND capacity_points <= 1000)', name=op.f('ck_ent_teams_capacity_bounds')),
    sa.ForeignKeyConstraint(['department_id'], ['ent_departments.department_id'], name=op.f('fk_ent_teams_department_id_ent_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('team_id', name=op.f('pk_ent_teams')),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_ent_teams_tenant_slug')
    )
    op.create_index(op.f('ix_ent_teams_department_id'), 'ent_teams', ['department_id'], unique=False)
    op.create_index(op.f('ix_ent_teams_tenant_id'), 'ent_teams', ['tenant_id'], unique=False)
    op.create_table('ent_engineer_profiles',
    sa.Column('engineer_profile_id', sa.String(length=64), nullable=False),
    sa.Column('current_team_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role_title', sa.String(length=128), nullable=True),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('employment_state', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_ent_engineer_profiles_valid_interval')),
    sa.ForeignKeyConstraint(['current_team_id'], ['ent_teams.team_id'], name=op.f('fk_ent_engineer_profiles_current_team_id_ent_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('engineer_profile_id', name=op.f('pk_ent_engineer_profiles'))
    )
    op.create_index(op.f('ix_ent_engineer_profiles_current_team_id'), 'ent_engineer_profiles', ['current_team_id'], unique=False)
    op.create_index(op.f('ix_ent_engineer_profiles_tenant_id'), 'ent_engineer_profiles', ['tenant_id'], unique=False)
    op.create_table('ent_projects',
    sa.Column('enterprise_project_id', sa.String(length=64), nullable=False),
    sa.Column('initiative_id', sa.String(length=64), nullable=True),
    sa.Column('owning_team_id', sa.String(length=64), nullable=True),
    sa.Column('legacy_project_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_target', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['ent_initiatives.initiative_id'], name=op.f('fk_ent_projects_initiative_id_ent_initiatives'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owning_team_id'], ['ent_teams.team_id'], name=op.f('fk_ent_projects_owning_team_id_ent_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('enterprise_project_id', name=op.f('pk_ent_projects')),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_ent_projects_tenant_slug')
    )
    op.create_index(op.f('ix_ent_projects_initiative_id'), 'ent_projects', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_ent_projects_legacy_project_id'), 'ent_projects', ['legacy_project_id'], unique=False)
    op.create_index(op.f('ix_ent_projects_owning_team_id'), 'ent_projects', ['owning_team_id'], unique=False)
    op.create_index(op.f('ix_ent_projects_tenant_id'), 'ent_projects', ['tenant_id'], unique=False)
    op.create_table('ent_repositories',
    sa.Column('repository_id', sa.String(length=64), nullable=False),
    sa.Column('owning_team_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_reference', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('default_branch', sa.String(length=128), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owning_team_id'], ['ent_teams.team_id'], name=op.f('fk_ent_repositories_owning_team_id_ent_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('repository_id', name=op.f('pk_ent_repositories')),
    sa.UniqueConstraint('tenant_id', 'provider', 'external_reference', name='uq_ent_repositories_external')
    )
    op.create_index(op.f('ix_ent_repositories_owning_team_id'), 'ent_repositories', ['owning_team_id'], unique=False)
    op.create_index(op.f('ix_ent_repositories_tenant_id'), 'ent_repositories', ['tenant_id'], unique=False)
    op.create_table('ent_sprints',
    sa.Column('sprint_id', sa.String(length=64), nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_ent_sprints_sprint_interval')),
    sa.ForeignKeyConstraint(['team_id'], ['ent_teams.team_id'], name=op.f('fk_ent_sprints_team_id_ent_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sprint_id', name=op.f('pk_ent_sprints')),
    sa.UniqueConstraint('tenant_id', 'team_id', 'name', name='uq_ent_sprints_team_name')
    )
    op.create_index(op.f('ix_ent_sprints_team_id'), 'ent_sprints', ['team_id'], unique=False)
    op.create_index(op.f('ix_ent_sprints_tenant_id'), 'ent_sprints', ['tenant_id'], unique=False)
    op.create_table('ent_deployments',
    sa.Column('deployment_id', sa.String(length=64), nullable=False),
    sa.Column('repository_id', sa.String(length=64), nullable=True),
    sa.Column('enterprise_project_id', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_reference', sa.String(length=256), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name=op.f('ck_ent_deployments_deployment_interval')),
    sa.ForeignKeyConstraint(['enterprise_project_id'], ['ent_projects.enterprise_project_id'], name=op.f('fk_ent_deployments_enterprise_project_id_ent_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['ent_repositories.repository_id'], name=op.f('fk_ent_deployments_repository_id_ent_repositories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('deployment_id', name=op.f('pk_ent_deployments')),
    sa.UniqueConstraint('tenant_id', 'provider', 'external_reference', name='uq_ent_deployments_external')
    )
    op.create_index(op.f('ix_ent_deployments_repository_id'), 'ent_deployments', ['repository_id'], unique=False)
    op.create_index(op.f('ix_ent_deployments_tenant_id'), 'ent_deployments', ['tenant_id'], unique=False)
    op.create_table('ent_engineer_capability_evidence',
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('engineer_profile_id', sa.String(length=64), nullable=False),
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('proficiency', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_ent_engineer_capability_evidence_confidence_bounds')),
    sa.CheckConstraint('proficiency IS NULL OR (proficiency >= 0 AND proficiency <= 100)', name=op.f('ck_ent_engineer_capability_evidence_proficiency_bounds')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_ent_engineer_capability_evidence_valid_interval')),
    sa.ForeignKeyConstraint(['capability_id'], ['ent_capabilities.capability_id'], name=op.f('fk_ent_engineer_capability_evidence_capability_id_ent_capabilities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engineer_profile_id'], ['ent_engineer_profiles.engineer_profile_id'], name=op.f('fk_ent_engineer_capability_evidence_engineer_profile_id_ent_engineer_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_ent_engineer_capability_evidence')),
    sa.UniqueConstraint('tenant_id', 'engineer_profile_id', 'capability_id', 'valid_from', name='uq_ent_eng_cap_evidence')
    )
    op.create_index(op.f('ix_ent_engineer_capability_evidence_capability_id'), 'ent_engineer_capability_evidence', ['capability_id'], unique=False)
    op.create_index(op.f('ix_ent_engineer_capability_evidence_engineer_profile_id'), 'ent_engineer_capability_evidence', ['engineer_profile_id'], unique=False)
    op.create_index(op.f('ix_ent_engineer_capability_evidence_tenant_id'), 'ent_engineer_capability_evidence', ['tenant_id'], unique=False)
    op.create_table('ent_engineer_skill_evidence',
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('engineer_profile_id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('proficiency', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_ent_engineer_skill_evidence_confidence_bounds')),
    sa.CheckConstraint('proficiency IS NULL OR (proficiency >= 0 AND proficiency <= 100)', name=op.f('ck_ent_engineer_skill_evidence_proficiency_bounds')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_ent_engineer_skill_evidence_valid_interval')),
    sa.ForeignKeyConstraint(['engineer_profile_id'], ['ent_engineer_profiles.engineer_profile_id'], name=op.f('fk_ent_engineer_skill_evidence_engineer_profile_id_ent_engineer_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['ent_skills.skill_id'], name=op.f('fk_ent_engineer_skill_evidence_skill_id_ent_skills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_ent_engineer_skill_evidence')),
    sa.UniqueConstraint('tenant_id', 'engineer_profile_id', 'skill_id', 'valid_from', name='uq_ent_eng_skill_evidence')
    )
    op.create_index(op.f('ix_ent_engineer_skill_evidence_engineer_profile_id'), 'ent_engineer_skill_evidence', ['engineer_profile_id'], unique=False)
    op.create_index(op.f('ix_ent_engineer_skill_evidence_skill_id'), 'ent_engineer_skill_evidence', ['skill_id'], unique=False)
    op.create_index(op.f('ix_ent_engineer_skill_evidence_tenant_id'), 'ent_engineer_skill_evidence', ['tenant_id'], unique=False)
    op.create_table('ent_incidents',
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('repository_id', sa.String(length=64), nullable=True),
    sa.Column('enterprise_project_id', sa.String(length=64), nullable=True),
    sa.Column('team_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_reference', sa.String(length=256), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('resolved_at IS NULL OR resolved_at >= started_at', name=op.f('ck_ent_incidents_incident_interval')),
    sa.ForeignKeyConstraint(['enterprise_project_id'], ['ent_projects.enterprise_project_id'], name=op.f('fk_ent_incidents_enterprise_project_id_ent_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['ent_repositories.repository_id'], name=op.f('fk_ent_incidents_repository_id_ent_repositories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['ent_teams.team_id'], name=op.f('fk_ent_incidents_team_id_ent_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('incident_id', name=op.f('pk_ent_incidents')),
    sa.UniqueConstraint('tenant_id', 'provider', 'external_reference', name='uq_ent_incidents_external')
    )
    op.create_index(op.f('ix_ent_incidents_repository_id'), 'ent_incidents', ['repository_id'], unique=False)
    op.create_index(op.f('ix_ent_incidents_tenant_id'), 'ent_incidents', ['tenant_id'], unique=False)
    op.create_table('ent_work_items',
    sa.Column('work_item_id', sa.String(length=64), nullable=False),
    sa.Column('enterprise_project_id', sa.String(length=64), nullable=True),
    sa.Column('initiative_id', sa.String(length=64), nullable=True),
    sa.Column('team_id', sa.String(length=64), nullable=True),
    sa.Column('sprint_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_reference', sa.String(length=256), nullable=False),
    sa.Column('work_item_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_project_id'], ['ent_projects.enterprise_project_id'], name=op.f('fk_ent_work_items_enterprise_project_id_ent_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiative_id'], ['ent_initiatives.initiative_id'], name=op.f('fk_ent_work_items_initiative_id_ent_initiatives'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sprint_id'], ['ent_sprints.sprint_id'], name=op.f('fk_ent_work_items_sprint_id_ent_sprints'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['ent_teams.team_id'], name=op.f('fk_ent_work_items_team_id_ent_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('work_item_id', name=op.f('pk_ent_work_items')),
    sa.UniqueConstraint('tenant_id', 'provider', 'external_reference', name='uq_ent_work_items_external')
    )
    op.create_index(op.f('ix_ent_work_items_enterprise_project_id'), 'ent_work_items', ['enterprise_project_id'], unique=False)
    op.create_index('ix_ent_work_items_project', 'ent_work_items', ['tenant_id', 'enterprise_project_id'], unique=False)
    op.create_index(op.f('ix_ent_work_items_tenant_id'), 'ent_work_items', ['tenant_id'], unique=False)
    op.add_column('capabilities', sa.Column('tenant_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_capabilities_tenant_id'), 'capabilities', ['tenant_id'], unique=False)
    op.add_column('engineers', sa.Column('tenant_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_engineers_tenant_id'), 'engineers', ['tenant_id'], unique=False)
    op.add_column('projects', sa.Column('tenant_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # Staged backfill: assign existing Phase 2 catalog rows to the legacy tenant.
    _backfill_legacy_tenant()


def _backfill_legacy_tenant() -> None:
    for table in ("capabilities", "engineers", "projects"):
        op.execute(
            sa.text(
                f"UPDATE {table} SET tenant_id = :tenant WHERE tenant_id IS NULL"
            ).bindparams(tenant=LEGACY_TENANT_ID)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_column('projects', 'tenant_id')
    op.drop_index(op.f('ix_engineers_tenant_id'), table_name='engineers')
    op.drop_column('engineers', 'tenant_id')
    op.drop_index(op.f('ix_capabilities_tenant_id'), table_name='capabilities')
    op.drop_column('capabilities', 'tenant_id')
    op.drop_index(op.f('ix_ent_work_items_tenant_id'), table_name='ent_work_items')
    op.drop_index('ix_ent_work_items_project', table_name='ent_work_items')
    op.drop_index(op.f('ix_ent_work_items_enterprise_project_id'), table_name='ent_work_items')
    op.drop_table('ent_work_items')
    op.drop_index(op.f('ix_ent_incidents_tenant_id'), table_name='ent_incidents')
    op.drop_index(op.f('ix_ent_incidents_repository_id'), table_name='ent_incidents')
    op.drop_table('ent_incidents')
    op.drop_index(op.f('ix_ent_engineer_skill_evidence_tenant_id'), table_name='ent_engineer_skill_evidence')
    op.drop_index(op.f('ix_ent_engineer_skill_evidence_skill_id'), table_name='ent_engineer_skill_evidence')
    op.drop_index(op.f('ix_ent_engineer_skill_evidence_engineer_profile_id'), table_name='ent_engineer_skill_evidence')
    op.drop_table('ent_engineer_skill_evidence')
    op.drop_index(op.f('ix_ent_engineer_capability_evidence_tenant_id'), table_name='ent_engineer_capability_evidence')
    op.drop_index(op.f('ix_ent_engineer_capability_evidence_engineer_profile_id'), table_name='ent_engineer_capability_evidence')
    op.drop_index(op.f('ix_ent_engineer_capability_evidence_capability_id'), table_name='ent_engineer_capability_evidence')
    op.drop_table('ent_engineer_capability_evidence')
    op.drop_index(op.f('ix_ent_deployments_tenant_id'), table_name='ent_deployments')
    op.drop_index(op.f('ix_ent_deployments_repository_id'), table_name='ent_deployments')
    op.drop_table('ent_deployments')
    op.drop_index(op.f('ix_ent_sprints_tenant_id'), table_name='ent_sprints')
    op.drop_index(op.f('ix_ent_sprints_team_id'), table_name='ent_sprints')
    op.drop_table('ent_sprints')
    op.drop_index(op.f('ix_ent_repositories_tenant_id'), table_name='ent_repositories')
    op.drop_index(op.f('ix_ent_repositories_owning_team_id'), table_name='ent_repositories')
    op.drop_table('ent_repositories')
    op.drop_index(op.f('ix_ent_projects_tenant_id'), table_name='ent_projects')
    op.drop_index(op.f('ix_ent_projects_owning_team_id'), table_name='ent_projects')
    op.drop_index(op.f('ix_ent_projects_legacy_project_id'), table_name='ent_projects')
    op.drop_index(op.f('ix_ent_projects_initiative_id'), table_name='ent_projects')
    op.drop_table('ent_projects')
    op.drop_index(op.f('ix_ent_engineer_profiles_tenant_id'), table_name='ent_engineer_profiles')
    op.drop_index(op.f('ix_ent_engineer_profiles_current_team_id'), table_name='ent_engineer_profiles')
    op.drop_table('ent_engineer_profiles')
    op.drop_index(op.f('ix_ent_teams_tenant_id'), table_name='ent_teams')
    op.drop_index(op.f('ix_ent_teams_department_id'), table_name='ent_teams')
    op.drop_table('ent_teams')
    op.drop_index(op.f('ix_ent_evidence_signals_tenant_id'), table_name='ent_evidence_signals')
    op.drop_index('ix_ent_evidence_signals_subject', table_name='ent_evidence_signals')
    op.drop_index(op.f('ix_ent_evidence_signals_ingestion_run_id'), table_name='ent_evidence_signals')
    op.drop_index(op.f('ix_ent_evidence_signals_data_source_id'), table_name='ent_evidence_signals')
    op.drop_table('ent_evidence_signals')
    op.drop_index(op.f('ix_ent_departments_tenant_id'), table_name='ent_departments')
    op.drop_index(op.f('ix_ent_departments_business_unit_id'), table_name='ent_departments')
    op.drop_table('ent_departments')
    op.drop_index(op.f('ix_ent_initiatives_tenant_id'), table_name='ent_initiatives')
    op.drop_index(op.f('ix_ent_initiatives_organization_id'), table_name='ent_initiatives')
    op.drop_table('ent_initiatives')
    op.drop_index(op.f('ix_ent_ingestion_runs_tenant_id'), table_name='ent_ingestion_runs')
    op.drop_index('ix_ent_ingestion_runs_source', table_name='ent_ingestion_runs')
    op.drop_index(op.f('ix_ent_ingestion_runs_data_source_id'), table_name='ent_ingestion_runs')
    op.drop_table('ent_ingestion_runs')
    op.drop_index(op.f('ix_ent_capability_skills_tenant_id'), table_name='ent_capability_skills')
    op.drop_index(op.f('ix_ent_capability_skills_skill_id'), table_name='ent_capability_skills')
    op.drop_index(op.f('ix_ent_capability_skills_capability_id'), table_name='ent_capability_skills')
    op.drop_table('ent_capability_skills')
    op.drop_index(op.f('ix_ent_capability_requirements_tenant_id'), table_name='ent_capability_requirements')
    op.drop_index(op.f('ix_ent_capability_requirements_subject_id'), table_name='ent_capability_requirements')
    op.drop_index(op.f('ix_ent_capability_requirements_capability_id'), table_name='ent_capability_requirements')
    op.drop_table('ent_capability_requirements')
    op.drop_index(op.f('ix_ent_business_units_tenant_id'), table_name='ent_business_units')
    op.drop_index(op.f('ix_ent_business_units_organization_id'), table_name='ent_business_units')
    op.drop_table('ent_business_units')
    op.drop_index(op.f('ix_ent_skills_tenant_id'), table_name='ent_skills')
    op.drop_table('ent_skills')
    op.drop_index(op.f('ix_ent_ownerships_tenant_id'), table_name='ent_ownerships')
    op.drop_index(op.f('ix_ent_ownerships_resource_id'), table_name='ent_ownerships')
    op.drop_index(op.f('ix_ent_ownerships_owner_id'), table_name='ent_ownerships')
    op.drop_table('ent_ownerships')
    op.drop_index(op.f('ix_ent_organizations_tenant_id'), table_name='ent_organizations')
    op.drop_table('ent_organizations')
    op.drop_index(op.f('ix_ent_dependencies_tenant_id'), table_name='ent_dependencies')
    op.drop_index(op.f('ix_ent_dependencies_target_id'), table_name='ent_dependencies')
    op.drop_index(op.f('ix_ent_dependencies_source_id'), table_name='ent_dependencies')
    op.drop_table('ent_dependencies')
    op.drop_index(op.f('ix_ent_data_sources_tenant_id'), table_name='ent_data_sources')
    op.drop_table('ent_data_sources')
    op.drop_index(op.f('ix_ent_capabilities_tenant_id'), table_name='ent_capabilities')
    op.drop_table('ent_capabilities')
    op.drop_index(op.f('ix_ent_availabilities_tenant_id'), table_name='ent_availabilities')
    op.drop_index(op.f('ix_ent_availabilities_target_id'), table_name='ent_availabilities')
    op.drop_table('ent_availabilities')
    # ### end Alembic commands ###
