"""Enterprise data-foundation enums (Phase 3 Prompt 1).

Pure domain enums with no ORM or framework dependencies. All values are stable,
deterministic identifiers; they must never be generated by an LLM.
"""

from enum import Enum


class OrganizationType(str, Enum):
    ENTERPRISE = "enterprise"
    SCALEUP = "scaleup"
    STARTUP = "startup"
    PUBLIC_SECTOR = "public_sector"


class TeamType(str, Enum):
    PLATFORM = "platform"
    PRODUCT = "product"
    DATA = "data"
    SRE = "sre"
    SECURITY = "security"
    ENABLING = "enabling"


class EmploymentState(str, Enum):
    """Non-sensitive operational status only. No private HR attributes."""

    ACTIVE = "active"
    ON_LEAVE = "on_leave"
    CONTRACTOR = "contractor"
    OFFBOARDING = "offboarding"
    INACTIVE = "inactive"


class EngineerLevel(str, Enum):
    JUNIOR = "junior"
    MID = "mid"
    SENIOR = "senior"
    STAFF = "staff"
    PRINCIPAL = "principal"


class StrategicPriority(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class Criticality(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class InitiativeStatus(str, Enum):
    PROPOSED = "proposed"
    ACTIVE = "active"
    AT_RISK = "at_risk"
    ON_HOLD = "on_hold"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class ProjectStatus(str, Enum):
    PLANNED = "planned"
    ACTIVE = "active"
    AT_RISK = "at_risk"
    BLOCKED = "blocked"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class RequirementSubjectType(str, Enum):
    INITIATIVE = "initiative"
    PROJECT = "project"


class CapabilityCategory(str, Enum):
    BACKEND = "backend"
    CLOUD = "cloud"
    AI = "ai"
    DATA = "data"
    DEVOPS = "devops"
    ARCHITECTURE = "architecture"
    SECURITY = "security"
    DELIVERY_EXECUTION = "delivery_execution"


class EvidenceStrengthSource(str, Enum):
    """Source of a capability/skill mapping. Deterministic, non-sensitive."""

    DECLARED = "declared"
    IMPORTED = "imported"
    INFERRED = "inferred"
    REVIEWED = "reviewed"


class RepositoryVisibility(str, Enum):
    PRIVATE = "private"
    INTERNAL = "internal"
    PUBLIC = "public"


class RepositoryState(str, Enum):
    ACTIVE = "active"
    ARCHIVED = "archived"


class WorkItemType(str, Enum):
    EPIC = "epic"
    STORY = "story"
    TASK = "task"
    BUG = "bug"
    SPIKE = "spike"


class WorkItemStatus(str, Enum):
    BACKLOG = "backlog"
    TODO = "todo"
    IN_PROGRESS = "in_progress"
    IN_REVIEW = "in_review"
    DONE = "done"
    CANCELLED = "cancelled"


class WorkItemPriority(str, Enum):
    P0 = "p0"
    P1 = "p1"
    P2 = "p2"
    P3 = "p3"


class SprintState(str, Enum):
    PLANNED = "planned"
    ACTIVE = "active"
    CLOSED = "closed"


class IncidentSeverity(str, Enum):
    SEV1 = "sev1"
    SEV2 = "sev2"
    SEV3 = "sev3"
    SEV4 = "sev4"


class IncidentState(str, Enum):
    OPEN = "open"
    MITIGATED = "mitigated"
    RESOLVED = "resolved"


class DeploymentEnvironment(str, Enum):
    DEVELOPMENT = "development"
    STAGING = "staging"
    PRODUCTION = "production"


class DeploymentStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    ROLLED_BACK = "rolled_back"


class EnterpriseEntityType(str, Enum):
    """Provider-neutral entity references for dependencies, ownership and evidence."""

    ORGANIZATION = "organization"
    BUSINESS_UNIT = "business_unit"
    DEPARTMENT = "department"
    TEAM = "team"
    ENGINEER_PROFILE = "engineer_profile"
    INITIATIVE = "initiative"
    PROJECT = "project"
    CAPABILITY = "capability"
    SKILL = "skill"
    REPOSITORY = "repository"
    WORK_ITEM = "work_item"
    SPRINT = "sprint"
    INCIDENT = "incident"
    DEPLOYMENT = "deployment"


class DependencyType(str, Enum):
    BLOCKS = "blocks"
    DEPENDS_ON = "depends_on"
    SHARES_CAPABILITY = "shares_capability"
    INTEGRATES_WITH = "integrates_with"
    OWNED_BY = "owned_by"


class DependencyStatus(str, Enum):
    ACTIVE = "active"
    RESOLVED = "resolved"
    SUPERSEDED = "superseded"


class OwnershipType(str, Enum):
    PRIMARY = "primary"
    SECONDARY = "secondary"
    CONTRIBUTOR = "contributor"
    SUPPORTING = "supporting"


class AvailabilityReason(str, Enum):
    PLANNED_LEAVE = "planned_leave"
    ALLOCATION = "allocation"
    INCIDENT_RESPONSE = "incident_response"
    ONBOARDING = "onboarding"
    UNKNOWN = "unknown"


class DataSourceType(str, Enum):
    GITHUB = "github"
    JIRA = "jira"
    AZURE_DEVOPS = "azure_devops"
    MANUAL = "manual"


class DataSourceStatus(str, Enum):
    REGISTERED = "registered"
    CONNECTED = "connected"
    DISABLED = "disabled"
    ERROR = "error"


class PermissionClassification(str, Enum):
    """Coarse sensitivity classification for imported evidence and sources."""

    PUBLIC = "public"
    INTERNAL = "internal"
    CONFIDENTIAL = "confidential"
    RESTRICTED = "restricted"


class IngestionRunType(str, Enum):
    FULL = "full"
    INCREMENTAL = "incremental"
    BACKFILL = "backfill"


class IngestionRunStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    PARTIAL = "partial"


class IngestionErrorCategory(str, Enum):
    NONE = "none"
    AUTHENTICATION = "authentication"
    RATE_LIMITED = "rate_limited"
    UPSTREAM_UNAVAILABLE = "upstream_unavailable"
    VALIDATION = "validation"
    INTERNAL = "internal"


class EvidenceSignalType(str, Enum):
    COMMIT = "commit"
    PULL_REQUEST = "pull_request"
    CODE_REVIEW = "code_review"
    WORK_ITEM_TRANSITION = "work_item_transition"
    DEPLOYMENT_EVENT = "deployment_event"
    INCIDENT_EVENT = "incident_event"
    OWNERSHIP_SIGNAL = "ownership_signal"
