export type ScenarioDefinition = {
  scenario_definition_id: string;
  tenant_id: string;
  name: string;
  description: string;
  target_type: string;
  target_id: string;
  scenario_kind: string;
  lifecycle_state: string;
  current_version: number;
};

export type ScenarioRun = {
  scenario_run_id: string;
  tenant_id: string;
  scenario_definition_id: string;
  scenario_version_id: string;
  target_type: string;
  target_id: string;
  state: string;
  run_mode: string;
  as_of_at: string;
  horizon_days: number;
  source_fingerprint: string;
  baseline_fingerprint: string;
  scenario_fingerprint: string;
  run_input_hash: string;
  graph_projection_version?: string | null;
  prediction_model_id?: string | null;
  prediction_baseline_version?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  nodes_examined?: number;
  edges_examined?: number;
  impacts_created?: number;
  sanitized_error_summary?: string | null;
  result_hash?: string | null;
  created_at: string | null;
};

export type ScenarioResult = {
  scenario_result_id: string;
  scenario_run_id: string;
  tenant_id: string;
  target_type: string;
  target_id: string;
  as_of_at: string;
  horizon_days: number;
  scenario_kind: string;
  baseline_summary?: Record<string, unknown>;
  simulated_summary?: Record<string, unknown>;
  delta_summary?: Record<string, unknown>;
  baseline_estimate_kind: string;
  simulated_estimate_kind: string;
  estimate_comparability: string;
  baseline_probability: number | null;
  simulated_probability: number | null;
  probability_delta?: number | null;
  baseline_risk_score: number | null;
  simulated_risk_score: number | null;
  risk_score_delta: number | null;
  baseline_risk_band?: string | null;
  simulated_risk_band?: string | null;
  affected_project_count: number;
  affected_initiative_count: number;
  affected_critical_initiative_count: number;
  findings_added_count: number;
  findings_removed_count: number;
  findings_worsened_count: number;
  findings_improved_count: number;
  data_quality_warnings: string[];
  applicability_warnings: string[];
  assumption_summary?: Record<string, unknown>;
  result_hash: string;
  created_at?: string | null;
};
